### ISSUE TITLE
Custom element doesn't exist: xiaomi-vacuum-card

### ISSUE THREAD

**Issue by habitoti** [benct/lovelace-xiaomi-vacuum-card#104]
I installed this vacuum card via HACS, it's properly listed under Dashboard resources. However I can't add an according card to a dashboard:
![2022-05-10_11-58-24](https://user-images.githubusercontent.com/220421/167603185-ec5d956b-20fe-4d24-aa51-fba849ee04c9.png)

The only log entry I am seeing in the log files says:

`
http://homeassistant.local:8123/hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js?hacstag=180229356301:18:23 TypeError: undefined is not a function (near '...css...')
`

System:
![2022-05-10_12-04-43](https://user-images.githubusercontent.com/220421/167604306-87d1b2bf-ea8a-421a-aef2-d4f61a918d20.png)

**Comment by kasper-leFevre** [comment]
having the same issue after upgrading to 2022.5.3
`Logger: frontend.js.latest.202205041
Source: components/system_log/__init__.py:190
First occurred: 11:31:38 (9 occurrences)
Last logged: 12:02:45

https://***.ui.nabu.casa/hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js:18:23 Uncaught TypeError: css is not a function
https://***.ui.nabu.casa/hacsfiles/kiosk-mode/kiosk-mode.js:38:26 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
https://***.ui.nabu.casa/hacsfiles/kiosk-mode/kiosk-mode.js:13:44 Uncaught TypeError: Cannot read properties of null (reading 'shadowRoot')`

**Comment by j-steve** [comment]
Same issue for me, though the root error message is slightly different:

```
Uncaught TypeError: css is not a function
    at Function.get styles [as styles] (xiaomi-vacuum-card.js?hacstag=180229356301:18:23)
    at Function.finalize (styles.ts:368:1)
    at Function.get observedAttributes [as observedAttributes] (styles.ts:368:1)
    at window.CustomElementRegistry.define (typography.js:181:1)
    at xiaomi-vacuum-card.js?hacstag=180229356301:296:20
    at xiaomi-vacuum-card.js?hacstag=180229356301:297:3
```

**Comment by habitoti** [comment]
Does work again with just released V4.2.0
